---
---
# Basic facts about Pladias
```{r, include=FALSE}
# install packages
source("scripts/01_packages.R")
```

```{r, include=FALSE}
query <- "SELECT s.description as name, s.color, COUNT(*) FROM atlas.records r JOIN atlas.record_validation_status s ON (s.id=r.validation_status) GROUP BY s.id ORDER BY s.priority DESC"
data <- dbGetQuery(db, query)

data$name <- factor(data$name, levels = unique(data$name))
```

## Quantitative description of the database
```{r }
table <- data %>%
    mutate(
    color_code = paste0("<span style='background-color:", color, ";'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span>"),
    count = format(count, big.mark = " ", decimal.mark = ","),
    ) %>%
    select(-color) %>%
    kable("html", escape = F, caption = "Records count according to the status of validity") %>%
    kable_styling(full_width = F)

plot <- ggplot(data, aes(x = name, y = count, fill = color)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  scale_fill_identity() +
  labs(title = "Records count according to the status of validity",
       x = "Status (called semafor)",
       y = "Records count") +
   theme(
       axis.text = element_text(size = 15),
       axis.title = element_text(size = 16),
       plot.title = element_text(size = 18, face = "bold")
       )
```
<div style="display: flex; justify-content: space-between;">
<div style="width: 30%;">
```{r }
table
```
</div>
<div style="width: 30%;">
&nbsp;
</div>
<div>
```{r }
plot
```
</div>
</div>